# Generated by Django 4.1.4 on 2023-12-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_devolucion_id_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
