# Generated by Django 4.1.4 on 2023-12-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_fecha_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
