# Generated by Django 4.1.4 on 2023-12-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_devolucion_cantidad_devuelta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolucion',
            old_name='fecha',
            new_name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='devolucion',
            name='precio',
        ),
        migrations.AlterField(
            model_name='devolucion',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(),
        ),
    ]
