# Generated by Django 3.1.2 on 2023-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_fecha_devolucion_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
